# Generated by Django 5.0.4 on 2024-05-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customer_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bio',
        ),
    ]
